---
title: "01_just-heatmaps"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 9
    toc: true
    toc_float:
      collapsed: false
    toc_depth: 5
    number_sections: true
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '5'
  word_document:
    toc: yes
    toc_depth: '5'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(#dev = c('pdf', 'png'),  # this embeds pdf and crates scrolable blocks
                      dev = c('png'), 
                      fig.align = 'center', 
                      fig.height = 9, 
                      fig.width = 9 ,
                      warning = FALSE, message = FALSE
                      )
# options(knitr.table.format = "html")

```



```{r, libraries.sources, echo=FALSE, results='hide', warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))


library(magrittr)
library(crayon)
library(RColorBrewer)
library(pheatmap)
library(grid)

```


# data

```{r}

fp = file.path('.')


fn1 = 'heatmap-all.xlsx'
df1 = openxlsx::read.xlsx(file.path(fp, fn1))

fn2 = 'heatmap-nonkin.xlsx'
df2 = openxlsx::read.xlsx(file.path(fp, fn2))

r1 = round(min(abs(range(df1[, 3:ncol(df1)], na.rm = TRUE)), abs(range(df2[, 2:ncol(df2)], na.rm = TRUE))))
r2 = round(max(abs(range(df1[, 3:ncol(df1)], na.rm = TRUE)), abs(range(df2[, 2:ncol(df2)], na.rm = TRUE))))

```


# heatmaps

<https://r-charts.com/colors/>

```{r}

data = as.matrix(df1[, 3:ncol(df1)])
rownames(data) = df1$shortname
dn = data
data[is.na(data)] = 0
dn = round(dn, 2)
dn[is.na(dn)] = ''

l = 20
mycol = rev(paletteer::paletteer_c("ggthemes::Red-Blue-White Diverging", l))
pie(rep(1, length(mycol)), col = mycol)
mycol = colorRampPalette(c("#104E8B", "white", "#B22222"))(l)
pie(rep(1, length(mycol)), col = mycol)


p = pheatmap(data, 
         col = mycol , # choose a colour scale for your data
         cluster_rows = F, cluster_cols = F, # set to FALSE if you want to remove the dendograms
         fontsize_row = 11,          # row label font size
         fontsize_col = 11,          # column label font size 
      
         angle_col = 90, # sample names at an angle
         show_colnames = T, show_rownames = T,
         breaks = seq(-r1, r1, length.out = l + 1),
         legend_breaks = seq(-r1, r1, length.out = r1*2 + 1), # ceiling((l + 1)/2)),
         number_color = "black", 
         fontsize_number = 10,
         display_numbers = dn,
         cellwidth = 30,
         cellheight = 15)

# Save the heatmap to a PDF file
pdf(paste0(gsub('\\..*', '', fn1), '_1.pdf'), width = 6, height = 6)  # Open PDF device
grid::grid.draw(p$gtable)                  # Explicitly draw the heatmap
dev.off()                                  # Close the PDF device


p = pheatmap(data, 
         col = mycol , # choose a colour scale for your data
         cluster_rows = F, cluster_cols = F, # set to FALSE if you want to remove the dendograms
         fontsize_row = 11,          # row label font size
         fontsize_col = 11,          # column label font size 
      
         angle_col = 90, # sample names at an angle
         show_colnames = T, show_rownames = T,
         breaks = seq(-r2, r2, length.out = l + 1),
         legend_breaks = seq(-r2, r2, length.out = r2 + 1), # ceiling((l + 1)/2)),
         number_color = "black", 
         fontsize_number = 10,
         display_numbers = dn,
         cellwidth = 30,
         cellheight = 15)

# Save the heatmap to a PDF file
pdf(paste0(gsub('\\..*', '', fn1), '_2.pdf'), width = 6, height = 6)  # Open PDF device
grid::grid.draw(p$gtable)                  # Explicitly draw the heatmap
dev.off()                                  # Close the PDF device


```


```{r}

data = as.matrix(df2[, 2:ncol(df2)])
rownames(data) = df2$shortname
dn = data
data[is.na(data)] = 0
dn = round(dn, 2)
dn[is.na(dn)] = ''

# l = 20
# mycol = rev(paletteer::paletteer_c("ggthemes::Red-Blue-White Diverging", l))
# pie(rep(1, length(mycol)), col = mycol)
# mycol = colorRampPalette(c("#104E8B", "white", "#B22222"))(l)
# pie(rep(1, length(mycol)), col = mycol)


p = pheatmap(data, 
         col = mycol , # choose a colour scale for your data
         cluster_rows = F, cluster_cols = F, # set to FALSE if you want to remove the dendograms
         fontsize_row = 11,          # row label font size
         fontsize_col = 11,          # column label font size 
      
         angle_col = 90, # sample names at an angle
         show_colnames = T, show_rownames = T,
         breaks = seq(-r1, r1, length.out = l + 1),
         legend_breaks = seq(-r1, r1, length.out = r1*2 + 1), # ceiling((l + 1)/2)),
         number_color = "black", 
         fontsize_number = 10,
         display_numbers = dn,
         cellwidth = 30,
         cellheight = 15)

# Save the heatmap to a PDF file
pdf(paste0(gsub('\\..*', '', fn2), '_1.pdf'), width = 6, height = 6)  # Open PDF device
grid::grid.draw(p$gtable)                  # Explicitly draw the heatmap
dev.off()                                  # Close the PDF device


p = pheatmap(data, 
         col = mycol , # choose a colour scale for your data
         cluster_rows = F, cluster_cols = F, # set to FALSE if you want to remove the dendograms
         fontsize_row = 11,          # row label font size
         fontsize_col = 11,          # column label font size 
      
         angle_col = 90, # sample names at an angle
         show_colnames = T, show_rownames = T,
         breaks = seq(-r2, r2, length.out = l + 1),
         legend_breaks = seq(-r2, r2, length.out = r2 + 1), # ceiling((l + 1)/2)),
         number_color = "black", 
         fontsize_number = 10,
         display_numbers = dn,
         cellwidth = 30,
         cellheight = 15)

# Save the heatmap to a PDF file
pdf(paste0(gsub('\\..*', '', fn2), '_2.pdf'), width = 6, height = 6)  # Open PDF device
grid::grid.draw(p$gtable)                  # Explicitly draw the heatmap
dev.off()                                  # Close the PDF device


```


# session Info


```{r, session_info}

sessionInfo()


```
