---
title: "00_v2022-v2025"
author: "zagor"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

fp = file.path('..', 'input')

fn = 'pss-dinar-nodes-restricted_2022-10-26.tsv'
n1 = as.data.frame(data.table::fread(file.path(fp, fn)))

fn = 'rxn-edges-public.tsv'
e2 = as.data.frame(data.table::fread(file.path(fp, fn)))
fn = 'rxn-nodes-public.tsv'
n2 = as.data.frame(data.table::fread(file.path(fp, fn)))


```


```{r}

e2$source = gsub('\\[.*', '', e2$source)
e2$target = gsub('\\[.*', '', e2$target)

n1$name = gsub('\\[.*', '', n1$name)
n2$name = gsub('\\[.*', '', n2$name)

```


```{r}

table(n2$name %in% n1$name)
table(n1$name %in% n2$name)

checkme = n1[!(n1$name %in% n2$name), c(1,5,7)]
print(checkme)

```


```{r}

e2$s1 = FALSE
e2$t1 = FALSE

table(e2$source %in% n1$name)
table(e2$target %in% n1$name)

e2$s1[e2$source %in% n1$name] = TRUE
e2$t1[e2$target %in% n1$name] = TRUE

e1 = e2[e2$s1 & e2$t1, ]



table(n2$name %in% n1$name)
n = n2[n2$name %in% n1$name, ]



table(sort(unique(c(e1$source, e1$target))) %in% n$name)
table(n$name %in% sort(unique(c(e1$source, e1$target))))
n = n[n$name %in% sort(unique(c(e1$source, e1$target))), ]


fn = 'pss-dinar-edges-restricted_2022-10-26_new-format.tsv'
data.table::fwrite(e1, file.path(fp, fn), sep = '\t')

fn = 'pss-dinar-nodes-restricted_2022-10-26_new-format.tsv'
data.table::fwrite(n, file.path(fp, fn), sep = '\t')


```

