---
title: "01_count"
author: "zagor"
date: "9 12 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

fp = file.path('..', 'input')
fn = 'ortholog_OCD_all_genes_spaceSep.tsv'

mylen = count.fields(file.path(fp,fn), sep = " ")
no_col <- max(mylen)


myFile = read.table(file.path(fp,fn),
                    sep=" ",
                    fill=TRUE,
                    header = F,
                    col.names=paste0("col", 1:no_col),
                    stringsAsFactors = FALSE,
                    comment.char = "@")

myFile[which(mylen == no_col),]

colnames(myFile)[1] = 'OCD'


data_long <- tidyr::gather(myFile, columnID, geneID, paste0("col", 2:no_col), factor_key=FALSE)
head(data_long)
rm(list=ls()[! ls() %in% c("data_long")])
gc()
data_long = data_long[,-2]

plants = unique(substr(data_long$geneID, 1, 3))
length(plants)
sort(plants)
myPlants = c('AT', 'PGS', 'Sot')

i1 = grep('^AT', data_long$geneID)
i2 = grep(myPlants[2], data_long$geneID)
i3 = grep(myPlants[3], data_long$geneID)
i = c(i1,i2,i3)

data_long_filtered = data_long[i,]
rm(list=ls()[! ls() %in% c("data_long_filtered")])
gc()

data_long_filtered_ordered = data_long_filtered[order(data_long_filtered$OCD),]
rm(list=ls()[! ls() %in% c("data_long_filtered_ordered")])
gc()

table(duplicated(data_long_filtered_ordered))


```


```{r}

fp = file.path('..', 'input')
fn = 'EXP2-geneIDs.txt'

myFile = read.table(file.path(fp,fn),
                    sep="\n",
                    fill=FALSE,
                    header = TRUE,
                    stringsAsFactors = FALSE,
                    comment.char = "@")

colnames(myFile) = names(myFile) = "geneID"
myFile$expression = myFile$geneID

data_long_filtered_ordered$geneID = gsub('\\.1\\.1', '', data_long_filtered_ordered$geneID)

myMerge = merge(data_long_filtered_ordered, myFile, all.x = TRUE, all.y = TRUE, by = 'geneID')

table(is.na(myMerge$OCD))

myOCD = sort(unique(myMerge[which(!is.na(myMerge$expression)),]$OCD))

myMerge_expressed = myMerge[myMerge$OCD %in% myOCD,]
myMerge_expressed_untranslated = myMerge[is.na(myMerge$OCD),]

myMerge_expressed_untranslated = myMerge_expressed_untranslated[order(myMerge_expressed_untranslated$geneID),]
myMerge_expressed_untranslated = myMerge_expressed_untranslated[,-3]

myMerge_expressed = myMerge_expressed[order(myMerge_expressed$OCD, myMerge_expressed$geneID),]


```

```{r}

fp = file.path('..', 'intermediate')
dir.create(fp)

write.table(myMerge_expressed_untranslated, 
            file = file.path(fp, "GFFmerged-not-in-OCD-all.txt"), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "-", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = c("escape"),
            fileEncoding = "UTF-8")

write.table(myMerge_expressed, 
            file = file.path(fp, "GFFmerged-in-OCD-all.txt"),
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "-", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = c("escape"),
            fileEncoding = "UTF-8")


```

```{r}

fp = curl::curl("https://raw.githubusercontent.com/NIB-SI/DiNAR/master/CKNs/GeI639CK5z5o7ynu")
CKN <- read.table(fp,
                  sep="\t", 
                  fill=TRUE, 
                  header = TRUE,
                  stringsAsFactors = FALSE,
                  comment.char = "~",
                  quote = NULL,
                  strip.white = TRUE,
                  allowEscapes = TRUE)

CKN = CKN[CKN$clusterID !=0, ]

CKN = CKN[, c(1, grep('clusterID', colnames(CKN)))]
colnames(myMerge_expressed)
colnames(CKN)[2] = 'AthCKN.clusterID'

myMerge_expressed = merge(myMerge_expressed, CKN, all.x = TRUE, all.y = FALSE, by = 'geneID')

```

```{r}

fp = curl::curl("https://raw.githubusercontent.com/NIB-SI/DiNAR/master/PIS/PIS_clade-Ath_genes.txt")
PIS <- read.table(fp,
                  sep="\t", 
                  fill=TRUE, 
                  header = FALSE,
                  stringsAsFactors = FALSE,
                  comment.char = "~",
                  quote = NULL,
                  strip.white = TRUE,
                  allowEscapes = TRUE)

colnames(PIS) = c('PIS.cladeID', 'geneID')

myMerge_expressed = merge(myMerge_expressed, PIS, all.x = TRUE, all.y = FALSE, by = 'geneID')

rm(list=ls()[! ls() %in% c("myMerge_expressed")])
gc()

```

```{r}

ind = sort(unique((c(which(!is.na(myMerge_expressed$AthCKN.clusterID)),
        which(!is.na(myMerge_expressed$PIS.cladeID))))))

myMerge_expressed$inNetwork = FALSE
myMerge_expressed$inNetwork[ind] = TRUE


i2 = intersect(grep('^AT', myMerge_expressed$geneID), which(!myMerge_expressed$inNetwork))
myMerge_expressed = myMerge_expressed[-i2,]
table(myMerge_expressed[grep('^AT', myMerge_expressed$geneID),]$inNetwork)
i1 = intersect(grep('^AT', myMerge_expressed$geneID), which(myMerge_expressed$inNetwork))
myOCD = unique(myMerge_expressed[i1,]$OCD)
length(myOCD)

myMerge_expressed = myMerge_expressed[myMerge_expressed$OCD %in% myOCD,]
i1 = grep('^AT', myMerge_expressed$geneID, invert = TRUE)
myMerge_expressed$geneID[i1] = myMerge_expressed$expression[i1]
myMerge_expressed = myMerge_expressed[, -3]

myMerge_expressed = myMerge_expressed[!is.na(myMerge_expressed$geneID),]
i1 = grep('^AT', myMerge_expressed$geneID, invert = TRUE)
table(myMerge_expressed[i1,]$OCD %in% myOCD)
myMerge_expressed = myMerge_expressed[, -ncol(myMerge_expressed)]

```

```{r}

fp = file.path('..', 'intermediate')

write.table(myMerge_expressed, 
            file = file.path(fp, "GFFmerged-in-OCD-all_in-Networks_long.txt"),
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "-", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = c("escape"),
            fileEncoding = "UTF-8")

```

```{r}

length(unique(myMerge_expressed$OCD))

# myMerge_expressed_wide = aggregate(geneID ~., myMerge_expressed, toString) not really
# library(data.table)
myMerge_expressed_wide.a = data.table::as.data.table(myMerge_expressed)[, toString(geneID), by = list(OCD)]
myMerge_expressed_wide.b = data.table::as.data.table(myMerge_expressed)[, toString(AthCKN.clusterID), by = list(OCD)]
myMerge_expressed_wide.c = data.table::as.data.table(myMerge_expressed)[, toString(PIS.cladeID), by = list(OCD)]

myMerge_expressed_wide = merge(myMerge_expressed_wide.a, myMerge_expressed_wide.b, all.x = TRUE, all.y = TRUE, by = 'OCD')
myMerge_expressed_wide = merge(myMerge_expressed_wide, myMerge_expressed_wide.c, all.x = TRUE, all.y = TRUE, by = 'OCD')

colnames(myMerge_expressed_wide)[2:ncol(myMerge_expressed_wide)] = c('geneIDs', 'Ath.CKN.cluIDs', 'PIS.cladeIDs')

myMerge_expressed_wide$Ath.CKN.cluIDs = lapply(myMerge_expressed_wide$Ath.CKN.cluIDs, function(x) unlist(as.list(strsplit(x, ", ")[[1]])))
myMerge_expressed_wide$Ath.CKN.cluIDs = lapply(myMerge_expressed_wide$Ath.CKN.cluIDs, function(x) sort(as.numeric(unique(x[x != 'NA']))))

myMerge_expressed_wide$PIS.cladeIDs = lapply(myMerge_expressed_wide$PIS.cladeIDs, function(x) unlist(as.list(strsplit(x, ", ")[[1]])))
myMerge_expressed_wide$PIS.cladeIDs = lapply(myMerge_expressed_wide$PIS.cladeIDs, function(x) sort(unique(x[x != 'NA'])))

myMerge_expressed_wide$geneIDs = lapply(myMerge_expressed_wide$geneIDs, function(x) unlist(as.list(strsplit(x, ", ")[[1]])))

n1 <- (unlist(rapply(myMerge_expressed_wide[,2], length, how="list")))
n2 <- (unlist(rapply(myMerge_expressed_wide[,3], length, how="list")))
n3 <- (unlist(rapply(myMerge_expressed_wide[,4], length, how="list")))



myMerge_expressed_wide$geneIDs = lapply(myMerge_expressed_wide$geneIDs, function(x) paste(x, collapse='|' ))
myMerge_expressed_wide$Ath.CKN.cluIDs = lapply(myMerge_expressed_wide$Ath.CKN.cluIDs, function(x) paste(x, collapse='|' ))
myMerge_expressed_wide$PIS.cladeIDs = lapply(myMerge_expressed_wide$PIS.cladeIDs, function(x) paste(x, collapse='|' ))

myMerge_expressed_wide$n1 = n1
myMerge_expressed_wide$n2 = n2
myMerge_expressed_wide$n3 = n3


rm(list=ls()[! ls() %in% c("myMerge_expressed_wide")])
gc()

# erer::write.list(myMerge_expressed_wide, 
#                  file = file.path(fp, "GFFmerged-in-OCD-all_in-Networks_wide.txt"))

myMerge_expressed_wide$geneIDs = as.character(myMerge_expressed_wide$geneIDs)
myMerge_expressed_wide$Ath.CKN.cluIDs = as.character(myMerge_expressed_wide$Ath.CKN.cluIDs)
myMerge_expressed_wide$PIS.cladeIDs = as.character(myMerge_expressed_wide$PIS.cladeIDs)

fp = file.path('..', 'intermediate')

write.table(myMerge_expressed_wide, 
            file = file.path(fp, "GFFmerged-in-OCD-all_in-Networks_wide.txt"),
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "-", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = c("escape"),
            fileEncoding = "UTF-8")



```

