---
title: "05_dummyFilesForDiNAR"
author: "zagor"
date: "22 12 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

fpo = file.path('..', 'output', 'dummyFilesForDiNAR')

dir.create(fpo)

fpi = file.path('..', 'intermediate')
fn = 'strict_RBBold-Ath-in-CKN-no-0_long-expressed-prioritised.txt'
  
combo = read.table(file.path(fpi,fn),
                    sep="\t",
                    fill=TRUE,
                    header = TRUE,
                    stringsAsFactors = FALSE,
                    comment.char = "@",
                   quote = NULL)

combo = combo[, c(grep('nodeID', colnames(combo)), grep('clusterID', colnames(combo)), grep('logFC', colnames(combo)))]

rm(list=ls()[! ls() %in% c("combo", 'fpo')])
gc()

rs = rowSums(combo[, 3:ncol(combo)])

hist(combo$clusterID, breaks = seq(1, 48, 1))
hist(rs, breaks = 100)

combo = combo[rs != 0,]
hist(combo$clusterID, breaks = seq(1, 48, 1))

```


```{r}

cnt = 1

for (i in 3:ncol(combo)) {
  print(colnames(combo)[i])
  tmp = combo[, c(1, i, i)]
  tmp[,3] = 0
  colnames(tmp) = c('geneID', 'logFC', 'p.value')
  
  write.table(tmp, 
              file = file.path(fpo, paste0(cnt, '_', colnames(combo)[i], '.txt')), 
              append = FALSE, 
              quote = FALSE, 
              sep = "\t",
              eol = "\n", na = "", 
              dec = ".", row.names = FALSE,
              col.names = TRUE, qmethod = c("escape"),
            fileEncoding = "UTF-8")
  cnt = cnt + 1
  
}

```

