---
title: "07_PSS-translation-prioritisation"
author: "zagor"
date: "23 12 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

fp = file.path('..', 'input')
fn = 'rbb_ath-vs-stuGFF_5_rbb-translation_filtered-long.txt'
RBBnew.GFFmerged.long <- read.table(file.path(fp, fn),
                     sep="\t", 
                     fill=TRUE, 
                     header = TRUE,
                     stringsAsFactors = FALSE,
                     comment.char = "~",
                     quote = NULL,
                     strip.white = TRUE,
                     allowEscapes = TRUE)

fp = file.path('..', 'intermediate', 'PSS_2021-12-22')
fn = 'translationTableExtract.txt'
PSS.translate <- read.table(file.path(fp, fn),
                     sep="\t", 
                     fill=TRUE, 
                     header = TRUE,
                     stringsAsFactors = FALSE,
                     comment.char = "~",
                     quote = NULL,
                     strip.white = TRUE,
                     allowEscapes = TRUE)

fp = file.path('..', 'input')
fn = 'mixedEXP2_AND_monoEXP1_logFC_padj_TMMcpm_narrow.txt'

mylen = count.fields(file.path(fp,fn), sep = "\t")
no_col <- max(mylen, na.rm = TRUE)
exp.values = read.table(file.path(fp,fn),
                    sep="\t",
                    skip = 1,
                    fill=TRUE,
                    header = TRUE,
                    # col.names=paste0("col", 1:no_col),
                    stringsAsFactors = FALSE,
                    comment.char = "@",
                    na.strings = '#N/A',
                    quote = NULL)

rownames(exp.values) = exp.values$GeneID
colnames(exp.values)[1] = 'geneID'
names(exp.values) = colnames(exp.values)

logFC = (exp.values[, grep('logFC', colnames(exp.values))])
logFC = as.matrix(logFC)
pval = (exp.values[, grep('adj\\.P\\.Val', colnames(exp.values))])
pval = as.matrix(pval)

pval[is.na(pval)] = 1
pval[pval >= 0.05] = 1


logFC[is.na(logFC)] = 0
logFC[which(pval == 1)] = 0


```

```{r}

PSS.translate$AthID = gsub('\\[', '', PSS.translate$AthID)
PSS.translate$AthID = gsub('\\]', '', PSS.translate$AthID)
PSS.translate$AthID = gsub(' ', '', PSS.translate$AthID)
PSS.translate$AthID = gsub('\\,', '\t', PSS.translate$AthID)

n = 0
m = max((sapply (1:nrow(PSS.translate), function(i) max((stringr::str_count(PSS.translate$AthID[i], "\t") + 1), n))))

tmp = stringr::str_split_fixed(PSS.translate$AthID, '\t', m)
colnames(tmp) = paste0('AthID', seq(1, ncol(tmp), 1))

PSS.translate = cbind(PSS.translate, tmp)

PSS.translate.x = tidyr::gather(PSS.translate, Ath.x, AthID.x, colnames(tmp), factor_key=FALSE)

PSS.translate.x = PSS.translate.x[, -3]
PSS.translate.x = PSS.translate.x[PSS.translate.x$AthID.x != '', ]

PSS.translate.x = PSS.translate.x[, -2]
colnames(PSS.translate.x)[2] = 'athID'
rownames(PSS.translate.x) = paste(PSS.translate.x$geneID, PSS.translate.x$athID)

```

```{r}

PSS.translate.x = merge(PSS.translate.x, RBBnew.GFFmerged.long, all.x = FALSE, all.y = FALSE, by = 'athID')
colnames(PSS.translate.x)[5] = 'potatoID'
colnames(exp.values)[1] = 'potatoID'

logFC[logFC == 0] = NA
logFC = as.data.frame(logFC)
logFC$potatoID = rownames(logFC)


PSS.translate.x = merge(PSS.translate.x, exp.values[, 1:4], all.x = FALSE, all.y = FALSE, by = 'potatoID')
PSS.translate.x = merge(PSS.translate.x, logFC, all.x = FALSE, all.y = FALSE, by = 'potatoID')

```


```{r}

fp = file.path('..', 'intermediate', 'PSS_2021-12-22')
fn = 'leftjoin-PSSnodes-RBB-exp.values.tsv'

write.table(PSS.translate.x, 
            file = file.path(fp, fn), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "-", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = c("escape"),
            fileEncoding = "UTF-8")


```

```{r}

rm(list=ls()[! ls() %in% c("PSS.translate.x")])
gc()


```

```{r}

logFC.starts.from.col = min(grep('logFC', colnames(PSS.translate.x)))

```

```{r}

PSSgenes = sort(unique(PSS.translate.x$geneID))
tmp = NULL

for (i in PSSgenes) {
  ind = which(PSS.translate.x$geneID == i)
  if (length(ind) > 1) { # (length(ind > 1)) for found, not length(ind) > 1 for multiple (1 or more, doesnt matter here)
    mysubset = PSS.translate.x[ind, ]
    e = sapply(1:nrow(mysubset), function(x) sum(!is.na(mysubset[x, logFC.starts.from.col:ncol(mysubset)])))
    f1 = sapply(1:nrow(mysubset), 
            function(x) ifelse(all(is.na(mysubset[x, logFC.starts.from.col:ncol(mysubset)])), 
                                0, 
                                mean(colMeans(abs(mysubset[x, logFC.starts.from.col:ncol(mysubset)]), na.rm = TRUE), na.rm = TRUE)))
    f2 = sapply(1:nrow(mysubset), 
            function(x) ifelse(all(is.na(mysubset[x, logFC.starts.from.col:ncol(mysubset)])), 
                                0, 
                                max(abs(mysubset[x, logFC.starts.from.col:ncol(mysubset)]), na.rm = TRUE)))
    g = which(e == max(e))
    h1 = which(f1[g] == max(f1[g]))
    h2 = which(f2[g] == max(f2[g]))
    k2 = ifelse(length(h1) > 1, h2, h1)
    k = ifelse(length(g) > 1, g[k2], g)
    
    tmp = rbind(tmp, mysubset[k,])
  } else { # no match
    tmp = rbind(tmp, PSS.translate.x[ind,]) # take first
  }
}

nrow(tmp) == length(PSSgenes)

prioritisedPSS =  tmp

```

```{r}

fp = file.path('..', 'intermediate', 'PSS_2021-12-22')
fn = 'leftjoin-PSSnodes-RBB-exp.values-prioritised.tsv'

write.table(prioritisedPSS, 
            file = file.path(fp, fn), 
            append = FALSE, 
            quote = FALSE, 
            sep = "\t",
            eol = "\n", 
            na = "-", 
            dec = ".", 
            row.names = FALSE,
            col.names = TRUE, 
            qmethod = c("escape"),
            fileEncoding = "UTF-8")

```


```{r}

fpo = file.path('..', 'output', 'dummyFilesForDiNAR_PSS')

dir.create(fpo)

combo = prioritisedPSS[, c(grep('geneID', colnames(prioritisedPSS)), grep('logFC', colnames(prioritisedPSS)))]

rs = rowSums(combo[, 2:ncol(combo)], na.rm = TRUE)

hist(rs, breaks = 100)
# combo = combo[rs != 0,]

combo[is.na(combo)] = 0.0


```

```{r}

cnt = 1

for (i in 2:ncol(combo)) {
  print(colnames(combo)[i])
  tmp = combo[, c(1, i, i)]
  tmp[,3] = 0
  colnames(tmp) = c('geneID', 'logFC', 'p.value')
  
  write.table(tmp, 
              file = file.path(fpo, paste0(cnt, '_', colnames(combo)[i], '.txt')), 
              append = FALSE, 
              quote = FALSE, 
              sep = "\t",
              eol = "\n", na = "", 
              dec = ".", row.names = FALSE,
              col.names = TRUE, qmethod = c("escape"),
            fileEncoding = "UTF-8")
  cnt = cnt + 1
  
}


```

