---
title: "merge-GSEA"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 8
    fig_height: 9
    toc: yes
    toc_float: true
    code_folding: show
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(#dev = c('pdf', 'png'),  # this embeds pdf and crates scrolable blocks
                      dev = c('png'), 
                      fig.align = 'center', 
                      fig.height = 9, 
                      fig.width = 8 ,
                      warning = FALSE, message = FALSE
                      )
# options(knitr.table.format = "html")

```



```{r, echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


set.seed(123456)

library(magrittr)

```

# gmt file

- contains all potential BINs

```{r}

fp = file.path('..', 'input')
fn = 'stu_PGSC-ITAG-merged.gmt.zip'
zip_path = file.path(fp, fn)

gmt_file = unzip(zip_path, list = TRUE)$Name[1]  # assumes first file is the .gmt

tmp = readLines(unz(zip_path, gmt_file))

n = stringr::str_count(tmp, pattern = '\t')
l = tmp[which(n == max(n))]
m = max(n + 1)

temp = stringr::str_split_fixed(tmp, '\t', m)

gmm = as.data.frame(temp)
gmm = data.frame(gmm[, 1])
colnames(gmm)[1] = 'NAME'

rm(temp)
gc()


```

# GSEA java results

## Monocoltures

```{r, echo=TRUE, warning=FALSE, message=FALSE}

fp = file.path('..', 'output', 'Monocultures')
fl = list.files(fp, recursive = TRUE, pattern = 'gsea_report_for_.*\\.tsv')

cnt = 1
dff = NULL
gmmPlus = gmm

for (i in fl){
  
  # print(i)
  
  df = data.table::fread(file.path(fp, i), header = TRUE)
  data.table::setDF(df)
  ind = grep('MSigDB|GS DETAILS|V12', colnames(df))
  df = df[, -ind]
  n = stringr::str_count(df$`LEADING EDGE`, pattern = ',')
  m = max(n+1)
  df$`LEADING EDGE` = gsub('tags=|list=|signal=', '', df$`LEADING EDGE`)
  temp = stringr::str_split_fixed(df$`LEADING EDGE`, ',', m)
  colnames(temp) = c('tags', 'list', 'signal')
  ind = grep('LEADING EDGE', colnames(df))
  df = df[, -ind]
  df = cbind(df, temp)
  # name = sub(pattern = "(.*)\\..*$", replacement = "\\1", basename(i))
  name = dirname(i)
  # name = gsub('gsea_report_for_', '', name)
  # name = stringr::str_replace(name, "_\\d+$", "")
  name = sub("_versus.*", "", name)
  print(name)

  
  if (!(cnt %% 2)) {
    dff = rbind(dff, df)
    colnames(dff)[2:ncol(dff)] = paste(colnames(dff), name, sep = '|')[2:ncol(dff)]
    # table(duplicated(dff$NAME))
    gmmPlus = merge(gmmPlus, dff, by = 'NAME', all.x = TRUE, all.y = TRUE)
    dff = NULL
  } else {
    dff = rbind(dff, df)
  }
  
  cnt = cnt + 1
  
  
}


rm(df)
gc()

```


```{r, echo=TRUE, warning=FALSE, message=FALSE}

# remove empty
rs = rowSums(is.na(gmmPlus[, 2:ncol(gmmPlus)]))
# table(rs)
# table(rs == (ncol(gmmPlus) - 1))
ind = which(rs == (ncol(gmmPlus) - 1))
gmmPlus = gmmPlus[-ind, ]


fpo = file.path('..', 'reports')
fn = 'GSEA_all-cols_Monocultures.txt'
write.table(gmmPlus,
            file = file.path(fpo, fn),
            append = FALSE,
            quote = FALSE,
            sep = "\t",
            eol = "\n",
            na = "NA",
            dec = ".",
            row.names = FALSE,
            col.names = TRUE,
            qmethod = c("escape"),
            fileEncoding = "UTF-8")



ind = c(grep('^NAME$', colnames(gmmPlus)),
        min(grep('SIZE', colnames(gmmPlus))),
        grep('^NES|^FDR|^tags', colnames(gmmPlus)))
gmmPlus = gmmPlus[, ind]
colnames(gmmPlus)[2] = 'SIZE'

gmmPlusM = gmmPlus[, c(
  "NAME",
  "SIZE",
  colnames(gmmPlus)[stringr::str_starts(colnames(gmmPlus), "NES\\|")],
  colnames(gmmPlus)[stringr::str_starts(colnames(gmmPlus), "FDR q-val\\|")],
  colnames(gmmPlus)[stringr::str_starts(colnames(gmmPlus), "tags\\|")]
)]
colnames(gmmPlusM)
rm(gmmPlus)



# fpo = file.path('..', 'output')
# fn = 'GSEA_few-cols.txt'
# write.table(gmmPlus,
#             file = file.path(fpo, fn),
#             append = FALSE,
#             quote = FALSE,
#             sep = "\t",
#             eol = "\n",
#             na = "-",
#             dec = ".",
#             row.names = FALSE,
#             col.names = TRUE,
#             qmethod = c("escape"),
#             fileEncoding = "UTF-8")



```

## Interactions

```{r, echo=TRUE, warning=FALSE, message=FALSE}

fp = file.path('..', 'output', 'Interactions')
fl = list.files(fp, recursive = TRUE, pattern = 'gsea_report_for_.*\\.tsv')

cnt = 1
dff = NULL
gmmPlus = gmm

for (i in fl){
  
  # print(i)
  
  df = data.table::fread(file.path(fp, i), header = TRUE)
  data.table::setDF(df)
  ind = grep('MSigDB|GS DETAILS|V12', colnames(df))
  df = df[, -ind]
  n = stringr::str_count(df$`LEADING EDGE`, pattern = ',')
  m = max(n+1)
  df$`LEADING EDGE` = gsub('tags=|list=|signal=', '', df$`LEADING EDGE`)
  temp = stringr::str_split_fixed(df$`LEADING EDGE`, ',', m)
  colnames(temp) = c('tags', 'list', 'signal')
  ind = grep('LEADING EDGE', colnames(df))
  df = df[, -ind]
  df = cbind(df, temp)
  # name = sub(pattern = "(.*)\\..*$", replacement = "\\1", basename(i))
  name = dirname(i)
  # name = gsub('gsea_report_for_', '', name)
  # name = stringr::str_replace(name, "_\\d+$", "")
  name = sub("_vs_.*", "", name)
  name = stringr::str_remove(name, "RNAseq_Bacillus_")
  name = stringr::str_remove(name, "_exp2")
  print(name)

  
  if (!(cnt %% 2)) {
    dff = rbind(dff, df)
    colnames(dff)[2:ncol(dff)] = paste(colnames(dff), name, sep = '|')[2:ncol(dff)]
    # table(duplicated(dff$NAME))
    gmmPlus = merge(gmmPlus, dff, by = 'NAME', all.x = TRUE, all.y = TRUE)
    dff = NULL
  } else {
    dff = rbind(dff, df)
  }
  
  cnt = cnt + 1
  
  
}


rm(gmm)
rm(df)
gc()

```


```{r, echo=TRUE, warning=FALSE, message=FALSE}

rs = rowSums(is.na(gmmPlus[, 2:ncol(gmmPlus)]))
ind = which(rs == (ncol(gmmPlus) - 1))
gmmPlus = gmmPlus[-ind, ]


fn = 'GSEA_all-cols_Interactions.txt'
write.table(gmmPlus,
            file = file.path(fpo, fn),
            append = FALSE,
            quote = FALSE,
            sep = "\t",
            eol = "\n",
            na = "NA",
            dec = ".",
            row.names = FALSE,
            col.names = TRUE,
            qmethod = c("escape"),
            fileEncoding = "UTF-8")



ind = c(grep('^NAME$', colnames(gmmPlus)),
        min(grep('SIZE', colnames(gmmPlus))),
        grep('^NES|^FDR|^tags', colnames(gmmPlus)))
gmmPlus = gmmPlus[, ind]
colnames(gmmPlus)[2] = 'SIZE'

gmmPlusI = gmmPlus[, c(
  "NAME",
  "SIZE",
  colnames(gmmPlus)[stringr::str_starts(colnames(gmmPlus), "NES\\|")],
  colnames(gmmPlus)[stringr::str_starts(colnames(gmmPlus), "FDR q-val\\|")],
  colnames(gmmPlus)[stringr::str_starts(colnames(gmmPlus), "tags\\|")]
)]
colnames(gmmPlusI)
rm(gmmPlus)





```


# Merge

```{r}

gmmFinal = merge(gmmPlusM, gmmPlusI, by = c('NAME', 'SIZE'), all.x = TRUE, all.y = TRUE)

gmmFinal = gmmFinal[, c(
  "NAME",
  "SIZE",
  colnames(gmmFinal)[stringr::str_starts(colnames(gmmFinal), "NES\\|")],
  colnames(gmmFinal)[stringr::str_starts(colnames(gmmFinal), "FDR q-val\\|")],
  colnames(gmmFinal)[stringr::str_starts(colnames(gmmFinal), "tags\\|")]
)]
colnames(gmmFinal)

```

# Filter

```{r}

threshold = 0.1

nes_cols = colnames(gmmFinal)[stringr::str_starts(colnames(gmmFinal), "NES\\|")]
fdr_cols = colnames(gmmFinal)[stringr::str_starts(colnames(gmmFinal), "FDR q-val\\|")]

suffixes = stringr::str_remove(nes_cols, "^NES\\|")

filtered_nes = lapply(seq_along(suffixes), function(i) {
  nes_col = paste0("NES|", suffixes[i])
  fdr_col = paste0("FDR q-val|", suffixes[i])
  if (fdr_col %in% colnames(gmmFinal)) {
    ifelse(gmmFinal[[fdr_col]] < threshold, gmmFinal[[nes_col]], NA)
  } else {
    NA
  }
})

names(filtered_nes) = paste0(suffixes)
filtered_nes_df = as.data.frame(filtered_nes)


gmmFiltered = dplyr::bind_cols(gmmFinal[c("NAME", "SIZE")], filtered_nes_df)

fn = 'GSEA_filtered.tsv'

write.table(gmmFiltered,
            file = file.path(fpo, fn),
            append = FALSE,
            quote = FALSE,
            sep = "\t",
            eol = "\n",
            na = "-",
            dec = ".",
            row.names = FALSE,
            col.names = TRUE,
            qmethod = c("escape"),
            fileEncoding = "UTF-8")

gmmFiltered[, -c(1, 2)] = lapply(gmmFiltered[, -c(1, 2)], function(x) sign(as.numeric(x)))

rs = rowSums(is.na(gmmFiltered[, 3:ncol(gmmFiltered)]))
ind = which(rs == (ncol(gmmFiltered) - 2))
gmmFiltered = gmmFiltered[-ind, ]



gmmLevels = gmmFiltered %>%
  dplyr::select(NAME) %>%
  dplyr::mutate(
    numeric_prefix = stringr::str_extract(NAME, "^[0-9.]+"),
    text_suffix = stringr::str_remove(NAME, "^[0-9.]+\\s*")
  ) %>%
  tidyr::separate(text_suffix, into = paste0("levelName_", 1:3), sep = "\\.", extra = "drop", fill = "right") %>%
  tidyr::separate(numeric_prefix, into = paste0("levelID_", 1:3), sep = "\\.", extra = "drop", fill = "right")
gmmFiltered = merge(gmmLevels, gmmFiltered, by = 'NAME', all.x = TRUE, all.y = TRUE)



fn = 'GSEA_filtered_sign.tsv'

write.table(gmmFiltered,
            file = file.path(fpo, fn),
            append = FALSE,
            quote = FALSE,
            sep = "\t",
            eol = "\n",
            na = "-",
            dec = ".",
            row.names = FALSE,
            col.names = TRUE,
            qmethod = c("escape"),
            fileEncoding = "UTF-8")


```


# session Info


```{r, echo=TRUE, warning=FALSE, message=FALSE}

sessionInfo()


```

