---
title: "Manual_log2FC"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: true
      smooth_scroll: true
    fig_caption: yes
    self_contained: yes
    fig_width: 12
    fig_height: 2
    number_sections: yes
    theme: flatly
    highlight: tango
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(#dev = c('pdf', 'png'),
                      dev = c('png', 'svg', 'pdf'), 
                      fig.align = 'center', 
                      fig.height = 2, 
                      fig.width = 12,
                      warning = FALSE, message = FALSE, echo = TRUE
                      )


```


```{r}

rm(list = ls(all = TRUE))
gc()


```


```{r}

library(magrittr)
library(data.table)
library(ggplot2)

```



# Exp1



```{r, input_Exp1}


fp = file.path('..', "input")
list.files(fp)

fn = 'Table_combinedInputs.xlsx'
wb = openxlsx::loadWorkbook(file.path(fp, fn))
sheet_names = names(wb)
sheet_name = grep("Experiment1", sheet_names, value = TRUE)


df = openxlsx::read.xlsx(xlsxFile = file.path(fp, fn),
                            sheet = sheet_name,
                            startRow = 10,
                            colNames = TRUE,
                            rowNames = FALSE,
                            detectDates = FALSE,
                            skipEmptyRows = TRUE,
                            skipEmptyCols = TRUE,
                            rows = NULL,
                            cols = NULL,
                            check.names = FALSE,
                            sep.names = ".",
                            namedRegion = NULL,
                            na.strings = "NA",
                            fillMergedCells = FALSE)

data.table::setDT(df)
df[, Sample.ID := NULL]
df[, Genotype := NULL]
df[, Strain := NULL]
df$Tissue = as.factor(trimws(df$Tissue))
df$Treatment = factor(trimws(df$Treatment), levels = c("noninoculated", "inoculated"))



```

# log2FC

```{r}


genes = c("StPti5", "St13-LOX")

log2fc_df1 = df %>%
  dplyr::group_by(Tissue, Time) %>%
  dplyr::summarise(dplyr::across(all_of(genes), ~ {
    group2 = log2(.x[Treatment == "inoculated"])
    group1 = log2(.x[Treatment == "noninoculated"])
    round(mean(group2, na.rm = TRUE) - mean(group1, na.rm = TRUE), 2)
  # }, .names = "log2FC_{.col}"), .groups = "drop")
  }, .names = "{.col}"), .groups = "drop")


```



# Exp2



```{r, input_Exp2}


fp = file.path('..', "input")
list.files(fp)

fn = 'Table_combinedInputs.xlsx'
wb = openxlsx::loadWorkbook(file.path(fp, fn))
sheet_names = names(wb)
sheet_name = grep("Experiment2", sheet_names, value = TRUE)

df = openxlsx::read.xlsx(xlsxFile = file.path(fp, fn),
                            sheet = sheet_name,
                            startRow = 10,
                            colNames = TRUE,
                            rowNames = FALSE,
                            detectDates = FALSE,
                            skipEmptyRows = TRUE,
                            skipEmptyCols = TRUE,
                            rows = NULL,
                            cols = NULL,
                            check.names = FALSE,
                            sep.names = ".",
                            namedRegion = NULL,
                            na.strings = "NA",
                            fillMergedCells = FALSE)

data.table::setDT(df)
df[, Sample.ID := NULL]
df[, Genotype := NULL]
df[, Strain := NULL]
df$Tissue = as.factor(trimws(df$Tissue))
df$Treatment = factor(trimws(df$Treatment), levels = c("noninoculated", "inoculated"))


```


# log2FC

```{r}


genes = c("StPti5", "St13-LOX")

log2fc_df2 = df %>%
  dplyr::group_by(Tissue, Time) %>%
  dplyr::summarise(dplyr::across(all_of(genes), ~ {
    group2 = log2(.x[Treatment == "inoculated"])
    group1 = log2(.x[Treatment == "noninoculated"])
    round(mean(group2, na.rm = TRUE) - mean(group1, na.rm = TRUE), 2)
  # }, .names = "log2FC_{.col}"), .groups = "drop")
  }, .names = "{.col}"), .groups = "drop")


```


```{r}



log2fc_df1_roots = log2fc_df1 %>% dplyr::filter(Tissue == "roots")
log2fc_df1_shoots = log2fc_df1 %>% dplyr::filter(Tissue == "shoots")
log2fc_df2_roots = log2fc_df2 %>% dplyr::filter(Tissue == "roots")


combined_df = dplyr::bind_rows(log2fc_df1_roots, log2fc_df2_roots, log2fc_df1_shoots)


combined_df = combined_df %>%
  dplyr::mutate(TissueTime = paste(Tissue, Time, sep = "_")) %>%
  dplyr::select(TissueTime, StPti5, `St13-LOX`)
combined_df = combined_df %>%
  dplyr::mutate(
    Tissue = stringr::str_extract(TissueTime, "^[^_]+"),
    Time_raw = stringr::str_extract(TissueTime, "(?<=_).*"),
    Time_value = as.numeric(stringr::str_extract(Time_raw, "\\d+")),
    Time_unit = stringr::str_extract(Time_raw, "[a-zA-Z]+"),
    Time_sort = dplyr::case_when(
      Time_unit == "min" ~ Time_value,
      Time_unit == "h" ~ Time_value * 60,
      TRUE ~ NA_real_
    )
  )
combined_df = combined_df %>%
  dplyr::arrange(Tissue, Time_sort)
combined_df = combined_df %>%
  dplyr::mutate(TissueTime = paste(Tissue, Time_raw, sep = "_")) %>%
  dplyr::select(TissueTime, StPti5, `St13-LOX`)


combined_df = combined_df %>%
  dplyr::mutate(
    TissueTime = make.unique(TissueTime, sep = "_")
  )


reshaped_df = combined_df %>%
  tidyr::pivot_longer(cols = c(StPti5, `St13-LOX`), names_to = "Gene", values_to = "log2FC") %>%
  tidyr::pivot_wider(names_from = TissueTime, values_from = log2FC)



heatmap_df = reshaped_df %>%
  tidyr::pivot_longer(-Gene, names_to = "TissueTime", values_to = "log2FC")
heatmap_df$TissueTime = factor(
  heatmap_df$TissueTime,
  levels = colnames(reshaped_df)[-1]  # exclude 'Gene'
)

ggplot(heatmap_df, aes(x = TissueTime, y = Gene, fill = log2FC)) +
  geom_tile(color = "grey80") +
  geom_text(aes(label = round(log2FC, 2)), size = 3) +  # Add numbers to tiles
  scale_fill_gradient2(
    low = "darkblue", mid = "white", high = "darkred",
    midpoint = 0,
    limits = c(min(heatmap_df$log2FC), max(heatmap_df$log2FC)),
    name = "log2FC"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ) +
  labs(title = "")

```


# sessionInfo

```{r}

sessionInfo()

```


